config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations', omniauth_callbacks: 'users/omniauth_callbacks', passwords: 'users/passwords' }

  resources :newsletters, only: [:create]
  resources :contacts, only: [:new, :create], path: 'contato', path_names: { :new => 'novo' }

  resources :static_pages, only: [:show], path: 'institucional'
  get 'sobre', controller: 'static_pages', action: 'about', path: 'sobre', as: :about
  get 'pontos-de-venda', controller: 'static_pages', action: 'pos', path: 'pontos-de-venda', as: :pos

  resources :products, only: [:index, :show], path: 'produtos' do
    collection do
      get 'search', as: :search, path: 'busca'
      get 'page', as: :page, path: 'pagina'
    end
    resources :favorites, only: [:create]
  end

  resources :carts, only: [:show], path: 'carrinho' do
    resources :cart_items, only: [:create, :update, :destroy], path: 'itens'
    collection do
      get 'set_shipping_method', as: :set_shipping_method, path: 'frete-selecionado'
    end
  end

  resource :carts, only: [], path: '' do
    collection do
      get 'check_shipping_price', as: :check_shipping_price, path: 'calcular-frete'
    end
  end

  resource :transactions, only: [:new], path: 'transacoes' do
    collection do
      post 'notification', as: :notification, path: 'notificacao'
      post 'create', as: :create, path: 'create'
      post 'new', as: :new, path: 'new'
      get 'success', as: :success, path: 'obrigado'
    end
  end

  get 'transacoes', to: 'transactions#index', as: :transactions_index

  resources :coupons, only: [], path: 'cupons' do
    collection do
      get 'add', as: :add, path: 'adicionar'
    end
  end

  resources :favorites, only: [:index, :destroy], path: 'favoritos'

  resources :artists, only: [:index], path: 'artistas' do
    collection do
      get 'page', as: :page, path: 'pagina'
    end
  end
  resources :artists, only: [:show], path: '/'

  mount NewRelicPing::Engine => '/status'

  root to: 'static_pages#show', id: '1'

end

app/models/static_page.rb
class StaticPage < ActiveRecord::Base
  extend FriendlyId
  friendly_id :slug_candidates, use: [:slugged, :reserved, :history]

  acts_as_paranoid

  scope :deleted, -> { only_deleted }

  has_many :faq_questions, dependent: :destroy
  accepts_nested_attributes_for :faq_questions, allow_destroy: true

  has_one :banner, as: :owner, dependent: :destroy, inverse_of: :owner
  accepts_nested_attributes_for :banner, allow_destroy: true

  has_one :meta_info, dependent: :destroy, as: :owner
  accepts_nested_attributes_for :meta_info, allow_destroy: true

  validates_presence_of :name, :title
  validates_uniqueness_of :name, case_sensitive: false

  def home?
    self.name == 'Home'
  end

  def faq?
    self.faq_questions.present?
  end

  def contact?
    self.name == 'Contato'
  end

  def faq_questions
    self.destroyed? ? super.with_deleted : super
  end

  def final_name
    self.footer_link_name || self.name
  end

  def active
    true
  end

  before_restore :restore_children

  private

    def restore_children
      FaqQuestion.restore self.faq_questions.only_deleted.map { |x| x.id }
    end

    def slug_candidates
      [
        :name
      ]
    end

    def should_generate_new_friendly_id?
      new_record? || slug.blank?
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def show
    @static_page = StaticPage.find params[:id]
    @banner = @static_page.banner

    if @static_page == StaticPage.where(name: 'Home').first
      @artists = Artist.active.public_ones.order('RANDOM()').limit(6)
      @products = Product.highlight.where(id: Product.ready.public_ones.pluck(:id)).includes(:artist).order('RANDOM()')

      @product_variations = ProductVariation.ready.where(default: true).where(product_id: @products.map { |x| x.id }).includes(:product_variation_photos).includes(product: :artist).includes(:product).sample(10)

      if @products.length < 9
        @products = Product.where(id: Product.ready.public_ones.pluck(:id)).includes(:artist).order('RANDOM()')
      end

      @keywords = Keyword.includes(:products).all.reject { |x| x.products.ready.public_ones.empty? }

      # @most_selled_products = Product.order('number_of_sells DESC')
      # @most_selled_color_products = ProductVariation.ready.where(default: true).where(product_id: @most_selled_products.pluck(:id)).includes(:product_variation_photos).includes(product: :artist).includes(:product).order('products.number_of_sells DESC').limit(10)

      # @most_recent_products = Product.where(id: Product.ready.public_ones.pluck(:id)).order('created_at DESC')

      @most_recent_product_variations = ProductVariation.ready.where(default: true).recent.limit(15)

      unless Rails.env.development?
        @instagram_photos = HTTParty.get("https://api.instagram.com/v1/tags/sejaMesclado/media/recent?count=10&access_token=#{ENV['INSTAGRAM_ACCESS_TOKEN']}")['data']
      end

      if params[:reset_password_token].present?
        @reset_user = User.find(params[:user_id])
        @reset_user.reset_password_token = params[:reset_password_token]
      end

      render 'home'
    elsif @static_page == StaticPage.where(name: 'FAQ').first
      render 'faq'
    end
  end

  def about
    @about = About.first
    @banner = @about.banner
  end

  def pos
  end
end

app/views/static_pages/about.html.haml
- meta og: { title: 'Sobre a Mesclado', type: 'website', url: request.url, image: @about.about_strips.first.photo.url(:big), description:  @about.about_strips.first.strip_text.html_safe }, title: 'Sobre', description: 'Mesclado é a mistura. Somos designers, fotógrafos, artistas plásticos, ilustradores. E nos juntamos para estampar t-shirts que tratamos como peças de arte'

- if @about.testimonials.present?
  .testimonials-area
    #testimonials
      - @about.testimonials.each do |test|
        .testimonial.text-center
          .test-title= "\"#{test.test_title}\""
          .test-author= test.test_author
          - if test.test_from
            .test-from= test.test_from
    - if @about.testimonials.length > 1
      - { left: 'prev', right: 'next' }.each do |k, v|
        %button{ type: 'button', role: 'button''', class: "#{k.to_s} carousel-control", data: { slide: v } }
          = fa_icon "angle-#{k.to_s}"

- if @about.about_strips.present?
  .strips-area
    - @about.about_strips.each_with_index do |strip, i|
      .strip{ class: "#{'inverted' if i == 0}" }
        .row
          .col-xs-15{ class: "#{'pull-right' unless i%2 == 0}" }
            .item.cover{ style: "background-image: url('#{strip.photo.url(:big)}');"}
          .col-xs-15.strip-content
            .vertical-aligned
              %h3= strip.strip_title
              .content= strip.strip_text.html_safe

.text-center.about-footer
  = link_to 'VEJA A GALERIA', products_path

app/views/static_pages/faq.html.haml
%h1.title= @static_page.name

.container
  - @static_page.faq_questions.each_with_index do |q, i|
    .accordion{ id: "accordion#{i}" }
      = link_to q.question.html_safe, "#collapse#{q.id}", data: { toggle: 'collapse', parent: "#accordion#{i}" }, class: 'collapsed'
      .collapse.answer{ id: "collapse#{q.id}" }
        = q.answer.html_safe


.faq-footer.text-center
  = link_to 'Ainda com dúvidas', new_contact_path

app/views/static_pages/home.html.haml
- meta og: { title: 'Mesclado', type: 'website', url: request.url }, description: 'Nós vemos as camisetas como mais uma plataforma de expressão artística. Somos designers, fotógrafos, artistas plásticos, ilustradores, grafiteiros... temos estilos bem diferentes, gostos peculiares e dominamos diferentes técnicas de expressão visual. Nos juntamos aqui para estampar t-shirts que tratamos como peças de arte'

.home
  = render 'outsiders/facebook_pixel_home'
  .row.home-product-variations-row
    .col-xs-10.home-black-block.text-center.full-height
      .vertical-aligned
        %h2 Mais vendidas
        / %p Lorem ipsum dolor sit amet, ei eum autem nullam appellantur. Elit cibo nostrum qui in.
        = link_to products_path, onclick: "ga('send', 'event', 'Home', 'Mais Vendidas', 'Conheça nossa Galeria');" do
          = fa_icon 'plus-circle inverse', text: 'Conheça toda a nossa galeria'
    .col-xs-20.full-height
      .products-tray.full-height
        - @product_variations.each do |pv|
          - product = pv.product
          - artist = product.artist
          .home-product-variation-thumb.full-height
            = image_tag pv.photo.url(:thumb)
            .overlay-area.text-center
              .thumb-details.text-center.details-top
                %p.product-name= product.name
                .artist-name
                  %span por
                  = link_to artist.name, artist
              = link_to 'Comprar', product, class: 'borderless-button', onclick: "ga('send', 'event', 'Home', 'Mais Vendidas', 'Comprar');"
              .thumb-details.text-center
                - if product.possible_promotions.present?
                  %p.price-no-discount= "de #{product.price_in_cents.to_brazilian_currency}"
                  %p.price= "por #{product.total_value.to_brazilian_currency}"
                - else
                  %p.price= product.total_value.to_brazilian_currency
      - { left: 'prev', right: 'next' }.each do |k, v|
        %button{ type: 'button', role: 'button''', class: "#{k.to_s} carousel-control", data: { slide: v } }
          = fa_icon "angle-#{k.to_s}"

  .row.home-product-variations-row
    .col-xs-20.full-height
      .products-tray.full-height
        - @most_recent_product_variations.each do |pv|
          - product = pv.product
          - artist = product.artist
          .home-product-variation-thumb.full-height
            = image_tag pv.photo.url(:thumb)
            .overlay-area.text-center
              .thumb-details.text-center.details-top
                %p.product-name= product.name
                .artist-name
                  %span por
                  = link_to artist.name, artist
              = link_to 'Comprar', product, class: 'borderless-button', onclick: "ga('send', 'event', 'Home', 'Novas Artes', 'Comprar');"
              .thumb-details.text-center
                - if product.possible_promotions.present?
                  %p.price-no-discount= "de #{product.price_in_cents.to_brazilian_currency}"
                  %p.price= "por #{product.total_value.to_brazilian_currency}"
                - else
                  %p.price= product.total_value.to_brazilian_currency
      - { left: 'prev', right: 'next' }.each do |k, v|
        %button{ type: 'button', role: 'button''', class: "#{k.to_s} carousel-control", data: { slide: v } }
          = fa_icon "angle-#{k.to_s}"
    .col-xs-10.home-black-block.text-center.full-height
      .vertical-aligned
        %h2 Novas artes
        / %p Lorem ipsum dolor sit amet, ei eum autem nullam appellantur. Elit cibo nostrum qui in.
        = link_to products_path, onclick: "ga('send', 'event', 'Home', 'Novas Artes', 'Conheça nossa Galeria');" do
          = fa_icon 'plus-circle inverse', text: 'Conheça toda a nossa galeria'

  .row.home-products
    .col-xs-30.text-center
      %h2 Galeria
      / %p Lorem ipsum dolor sit amet, ei eum autem nullam appellantur. Elit cibo nostrum qui in. Malorum imperdiet laboramus ne his.


  .products-organizer.text-center
    - if @keywords.present?
      .organize-products.keywords
        .organizer-bt
          Tags
          = fa_icon 'angle-down 2x'
        .organizer-popup
          .search-keywords
            %input{ type: 'text' }
            = fa_icon 'search'
          .possible-keywords
            - @keywords.each do |k|
              = link_to k.name.capitalize, products_path(tag: k.name), data: { key: k.name }
    .divider
    / .organize-products.price
    /   .organizer-bt
    /     Preço
    /     = fa_icon 'angle-down 2x'
    /   .organizer-popup
    /     = link_to 'Crescente', products_path(price: 'ASC')
    /     = link_to 'Decrescente', products_path(price: 'DESC')
    = link_to products_path, class: 'random-products-link' do
      Random
      = fa_icon 'random'

  - if @products.any?
    = render 'shared/list', list: @products.limit(27), n: 9, page: 'products/page', ajax_url: '/produtos/pagina', gallery: products_path, with_ga: true

  .row.home-artists-row
    .col-xs-20.full-height
      - @artists.in_groups(2) do |g|
        .row.inner-artist-row
          = render partial: 'artists/thumb', collection: g, as: :artist, locals: { div_class: 'col-xs-10 full-height' }, ga_active: true
          -# - g.each do |artist|
          -#   .col-xs-10.full-height
          -#     = render 'artists/thumb', artist: artist, type: :medium
    .col-xs-10.full-height.home-black-block.text-center
      .vertical-aligned
        %h2 Artistas
        / %p Lorem ipsum dolor sit amet, ei eum autem nullam appellantur. Elit cibo nostrum qui in. Malorum imperdiet laboramus ne his. Legimus delicatissimi eos et, dolor posidonium mel ut.
        = link_to artists_path, onclick: "ga('send', 'event', 'Home', 'Artistas', 'Conheça Nossos Artistas');" do
          = fa_icon 'plus-circle inverse', text: 'Conheça nossos artistas'

  - if @instagram_photos.present?
    .row.social-footer
      .row
        .col-xs-30.social-title.text-center
          %span No instagram
          = fa_icon 'instagram 3x'
          %span poste #SEJAMESCLADO
      .row
        .col-xs-30.social-content
          .row.instagram-photos-row
            - @instagram_photos.first(6).each do |ip|
              .col-xs-5
                = link_to image_tag(ensure_https(ip['images']['low_resolution']['url'])), ip['link'], target: '_blank', class: 'grayscale'
          .row.instagram-photos-row
            - groups = @instagram_photos.last(4).in_groups(2)
            - groups.first.each do |ip|
              .col-xs-5
                = link_to image_tag(ensure_https(ip['images']['low_resolution']['url'])), ip['link'], target: '_blank', class: 'grayscale'
            .col-xs-5
              / = link_to 'https://www.pinterest.com/sejamesclado/', class: 'social-square pinterest-square', target: '_blank' do
              = link_to 'https://instagram.com/sejamesclado', class: 'social-square pinterest-square', target: '_blank' do
                .vertical-aligned
                  = fa_icon 'instagram 3x'
                  %p Siga MESCLADO no Instagram
            .col-xs-5
              = link_to 'https://www.facebook.com/pages/sejaMesclado/1402779966656313', class: 'social-square facebook-square', target: '_blank' do
                .vertical-aligned
                  = fa_icon 'facebook 3x'
                  %p Curta MESCLADO no Facebook
            - groups.last.each do |ip|
              .col-xs-5
                = link_to image_tag(ensure_https(ip['images']['low_resolution']['url'])), ip['link'], target: '_blank', class: 'grayscale'

app/views/static_pages/pos.html.haml
%ul#pos-list.container
  - @pos.each do |pos|
    %li.pos.row
      .col-xs-8
        = image_tag pos.photo.url(:standard)
      .col-xs-22
        %h2= pos.name
        %p= pos.description
        %p.address
          %span.title= "Endereço: "
          = pos.address

app/views/static_pages/show.html.haml
%h1.title= @static_page.name

.container
  .static_page_content= @static_page.content.html_safe