config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations', omniauth_callbacks: 'users/omniauth_callbacks', passwords: 'users/passwords' }

  resources :newsletters, only: [:create]
  resources :contacts, only: [:new, :create], path: 'contato', path_names: { :new => 'novo' }

  resources :static_pages, only: [:show], path: 'institucional'
  get 'sobre', controller: 'static_pages', action: 'about', path: 'sobre', as: :about
  get 'pontos-de-venda', controller: 'static_pages', action: 'pos', path: 'pontos-de-venda', as: :pos

  resources :products, only: [:index, :show], path: 'produtos' do
    collection do
      get 'search', as: :search, path: 'busca'
      get 'page', as: :page, path: 'pagina'
    end
    resources :favorites, only: [:create]
  end

  resources :carts, only: [:show], path: 'carrinho' do
    resources :cart_items, only: [:create, :update, :destroy], path: 'itens'
    collection do
      get 'set_shipping_method', as: :set_shipping_method, path: 'frete-selecionado'
    end
  end

  resource :carts, only: [], path: '' do
    collection do
      get 'check_shipping_price', as: :check_shipping_price, path: 'calcular-frete'
    end
  end

  resource :transactions, only: [:new], path: 'transacoes' do
    collection do
      post 'notification', as: :notification, path: 'notificacao'
      post 'create', as: :create, path: 'create'
      post 'new', as: :new, path: 'new'
      get 'success', as: :success, path: 'obrigado'
    end
  end

  get 'transacoes', to: 'transactions#index', as: :transactions_index

  resources :coupons, only: [], path: 'cupons' do
    collection do
      get 'add', as: :add, path: 'adicionar'
    end
  end

  resources :favorites, only: [:index, :destroy], path: 'favoritos'

  resources :artists, only: [:index], path: 'artistas' do
    collection do
      get 'page', as: :page, path: 'pagina'
    end
  end
  resources :artists, only: [:show], path: '/'

  mount NewRelicPing::Engine => '/status'

  root to: 'static_pages#show', id: '1'

end

app/models/cart_item.rb
class CartItem < ActiveRecord::Base
  acts_as_paranoid

  belongs_to :product_variation
  belongs_to :cart, inverse_of: :cart_items
  belongs_to :product_variation_size
  belongs_to :promotion, inverse_of: :cart_items
  belongs_to :coupon, inverse_of: :cart_items

  serialize :values_ids
  serialize :values_names
  serialize :variation_values_hash
  serialize :product_variation_hash
  serialize :product_hash
  serialize :artist_hash

  validates_presence_of :amount, :unit_price_in_cents, :product_variation
  validates :amount, numericality: { only_integer: true }
  validates :unit_price_in_cents, numericality: { only_integer: true }
  validates :discount_in_cents, numericality: { only_integer: true }

  def total_price
    self.amount * self.total_unit_price
  end

  def total_price_with_coupon
    self.amount * self.unit_price_with_coupon
  end

  def total_unit_price
    self.unit_price_in_cents - self.discount_in_cents
  end

  def total_price_no_discount
    self.amount * self.unit_price_in_cents
  end

  def unit_price_with_coupon
    if self.with_discount_from_coupon?
      self.cart.coupon.promotion.promotion_profile.advantage.advantage_profile.final_value(self.total_unit_price)
    else
      self.total_unit_price
    end
  end

  def with_discount_from_coupon?
    if self.cart.coupon.present?
      items = self.cart.coupon.coupon_items(self.cart)
      unless items.nil?
        if items.include? self
          return true
        end
      end
    end
    return false
  end

  def add_amount value
    self.update_attributes(amount: self.amount + value)
  end

  def product_name
    self.product_hash['name'] if self.product_hash.present?
  end

  def product_id
    self.product_hash['id'] if self.product_hash.present?
  end

  def artist_name
    self.artist_hash['name'] if self.artist_hash.present?
  end

  def artist_id
    self.artist_hash['id'] if self.artist_hash.present?
  end

  def photo
    self.product_variation_hash['photo_url'] if self.product_variation_hash.present?
  end

  def name
    "#{self.product_variation_hash['name']} - #{self.product_variation_size.name}"
  end

  def update_promotions
    self.discount_in_cents = self.product_variation.product.discount
    self.promotion = self.product_variation.product.best_promotion
    self.save(validate: false)
  end

  def check_if_promotion_is_valid?
    if self.promotion.present?
      product = self.product_variation.product
      artist = product.artist
      unless self.promotion.valid_for?(product) or self.promotion.valid_for?(artist)
        self.promotion = nil
        self.coupon = nil
        self.discount_in_cents = 0
        self.save(validate: false)
      end
    end
  end

  before_validation :set_numbers
  after_validation :set_extra_variables, if: -> { self.cart.payment_date.nil? }
  after_commit :suicide_if_no_amount, if: -> { self.amount == 0 }

  private

    def set_extra_variables
      pv = self.product_variation

      # Set hash of the product variation values attributes
      variation_values = pv.product_variation_type_values
      self.values_ids = variation_values.map { |x| x.id }
      self.values_names = variation_values.map { |x| x.name }
      self.variation_values_hash = variation_values.map { |x| x.attributes.merge('photo_url' => x.photo.url(:icon), 'selected_photo_url' => x.selected_photo.url(:icon)) }

      # Set the name of the size
      self.size = self.product_variation_size.name

      # Set hash of the product attributes
      self.product_hash = pv.product.attributes.merge('photo_url' => pv.product.photo.url(:standard))

      # Set hash of the artist attributes
      self.artist_hash = pv.product.artist.attributes

      # Set hash of the product_variation attributes
      self.product_variation_hash = pv.attributes.merge('photo_url' => pv.photo.url(:thumb), 'name' => pv.name)
    end

    def suicide
      self.destroy
    end

    def set_numbers
      self.unit_price_in_cents ||= 0
      self.discount_in_cents ||= 0
    end
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  layout false
  respond_to :js

  def create
    if params[:redirect_to_cart] == 'true' or params[:redirect_to_cart] == true
      @redirect_to_cart = true
    end

    if params['0'].blank?
      @no_size = true
      # flash.now[:error] = "Você deve escolher um tamanho para comprar um produto."
    else
      @no_size = nil
      @cart = get_cart
      @cart.add_product_variation params['product_variation_id'], params['0']
    end
  end

  def update
    @cart = get_cart
    @cart.update_attributes(shipping_hash: nil, shipping_price_in_cents: 0)
    @cart_item = CartItem.find params[:id]
    @cart_item.update_attributes(amount: params['amount'].to_i)
  end

  def destroy
    @cart = get_cart
    @cart.remove_product_variation params[:id]
  end
end

app/views/cart_items/_floating_thumb.html.haml
.floating-cart-item-thumb{ data: { id: cart_item.id } }
  .row
    .col-xs-6
      = image_tag cart_item.photo, class: 'img-circle'
    .col-xs-21.text-center
      %p.name=link_to cart_item.product_name, product_path(cart_item.product_id)
      %p.artist
        por
        = link_to cart_item.artist_name, artist_path(cart_item.artist_id)
      %p.values
        %span= "em #{cart_item.values_names.join(' | ')} | "
        %span= "Tamanho #{cart_item.size}"
      %p.no-discount-price
        - if cart_item.discount_in_cents > 0 || cart_item.with_discount_from_coupon?
          %span.line-through= "de #{cart_item.unit_price_in_cents.to_brazilian_currency}"
          %span= "por"
        - else
          %span Preço unitário:
        %span= "#{cart_item.unit_price_with_coupon.to_brazilian_currency}"
      %p.price= "Quantidade: #{cart_item.amount}, Total: #{cart_item.total_price_with_coupon.to_brazilian_currency}"
    .col-xs-3.text-center
      = link_to cart_cart_item_path(cart_id: get_cart.id, id: cart_item.id), method: :delete, remote: true, class: 'remove-item-link' do
        = fa_icon 'trash-o', onclick: "window.start_loading();"

app/views/cart_items/create.js.erb
<% if @cart.nil? %>
  window.stop_loading();
  <% flash.each do |name, msg| %>
    <%= add_gritter msg, :class_name => "gritter-#{name}", title: I18n.t("gflash.titles.#{name}") %>
  <% end %>
  <% if @no_size %>
    $('#variations-modal').modal('show');
  <% end %>
<% else %>
  <%= render 'carts/update_cart_page.js.erb', action: :create %>
  <% if @redirect_to_cart %>
    window.start_loading();
    window.location.href = "<%= cart_path(@cart) %>";
  <% end %>
<% end %>

app/views/cart_items/destroy.js.erb
<%= render 'carts/update_cart_page.js.erb', action: :destroy %>

app/views/cart_items/update.js.erb
<%= render 'carts/update_cart_page.js.erb', action: :update %>