config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations', omniauth_callbacks: 'users/omniauth_callbacks', passwords: 'users/passwords' }

  resources :newsletters, only: [:create]
  resources :contacts, only: [:new, :create], path: 'contato', path_names: { :new => 'novo' }

  resources :static_pages, only: [:show], path: 'institucional'
  get 'sobre', controller: 'static_pages', action: 'about', path: 'sobre', as: :about
  get 'pontos-de-venda', controller: 'static_pages', action: 'pos', path: 'pontos-de-venda', as: :pos

  resources :products, only: [:index, :show], path: 'produtos' do
    collection do
      get 'search', as: :search, path: 'busca'
      get 'page', as: :page, path: 'pagina'
    end
    resources :favorites, only: [:create]
  end

  resources :carts, only: [:show], path: 'carrinho' do
    resources :cart_items, only: [:create, :update, :destroy], path: 'itens'
    collection do
      get 'set_shipping_method', as: :set_shipping_method, path: 'frete-selecionado'
    end
  end

  resource :carts, only: [], path: '' do
    collection do
      get 'check_shipping_price', as: :check_shipping_price, path: 'calcular-frete'
    end
  end

  resource :transactions, only: [:new], path: 'transacoes' do
    collection do
      post 'notification', as: :notification, path: 'notificacao'
      post 'create', as: :create, path: 'create'
      post 'new', as: :new, path: 'new'
      get 'success', as: :success, path: 'obrigado'
    end
  end

  get 'transacoes', to: 'transactions#index', as: :transactions_index

  resources :coupons, only: [], path: 'cupons' do
    collection do
      get 'add', as: :add, path: 'adicionar'
    end
  end

  resources :favorites, only: [:index, :destroy], path: 'favoritos'

  resources :artists, only: [:index], path: 'artistas' do
    collection do
      get 'page', as: :page, path: 'pagina'
    end
  end
  resources :artists, only: [:show], path: '/'

  mount NewRelicPing::Engine => '/status'

  root to: 'static_pages#show', id: '1'

end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  skip_before_filter :verify_authenticity_token, only: :notification


  def index
    if user_signed_in?
      @carts = current_user.closed_carts
    else
      flash.now[:error] = "Você precisa estar logado para acessar essa página."
      redirect_to root_path
    end
  end

  def new


      if user_signed_in?

        @cart = get_cart
        if @cart.shipping_hash.blank?
          flash[:error] = "Antes de comprar, por favor preencha o seu CEP e clique em calcular frete."
          redirect_to cart_path(@cart, no_shipping: true)
        else

          @session_id = (PagSeguro::Session.create).id

          puts "---------------------> #{@session_id}"

          @cart_id = @cart.id
          @total_price = @cart.total_price / 100.00



          address = Address.find_by_owner_id(current_user.id)

          unless address.nil? || address == 0
            @endereco = address
          else
            @endereco = Address.new
          end

        end

      else
        # flash[:error] = "Para poder efetuar compras é necessário estar logado."
        session[:after_redirect] = cart_path(current_cart)
        redirect_to cart_path(current_cart, login_modal: true)
      end

  end

  def create
    if user_signed_in?
      if current_user.cpf.blank?
        flash[:error] = "Para poder efetuar compras é necessário que um CPF seja cadastrado."
        session[:after_redirect] = cart_path(current_cart)
        redirect_to edit_user_registration_path(current_user)
      elsif current_user.last_name.blank?
        flash[:error] = "Para poder efetuar compras é necessário que o seu nome esteja cadastrado com o sobrenome também."
        session[:after_redirect] = cart_path(current_cart)
        redirect_to edit_user_registration_path(current_user)
      else
        @cart = get_cart
        if @cart.shipping_hash.blank?
          flash[:error] = "Antes de comprar, por favor preencha o seu CEP e clique em calcular frete."
          redirect_to cart_path(@cart, no_shipping: true)
        else


          address = Address.find_by_owner_id(current_user.id)

          unless address.nil? || address == 0

            if address.update_attributes(address_params)
              endereco = 'ok'
            else
              flash[:error] = "Endereço não pôde ser atualizado"
              redirect_to :action => 'new'
            end

          else

            addrs = Address.new(address_params)

            if addrs.save
              endereco = 'ok'
            else
              puts "ERRO AO ADICIONAR ENDEREÇO ---------> #{addrs.errors.full_messages}"
              flash[:error] = "Endereço não pôde ser cadastrado"
              redirect_to :action => 'new'
            end

          end

          if endereco == 'ok'

            puts "PARAMETRO CEP -----> #{params[:address][:zip_code]}"
            puts "PARAMETRO RUA -----> #{params[:address][:street]}"
            puts "PARAMETRO NUMERO -----> #{params[:address][:street_number]}"
            puts "PARAMETRO COMPLEMENTO -----> #{params[:address][:complement]}"
            puts "PARAMETRO BAIRRO -----> #{params[:address][:neighborhood]}"
            puts "PARAMETRO CIDADE -----> #{params[:address][:city]}"
            puts "PARAMETRO ESTADO -----> #{params[:address][:state]}"


            @transaction = @cart.transactions.new
              
            payment = @cart.create_pagseguro_transparente(params[:checkout_card_bandeira], params[:checkout_tipo_pagamento], params[:checkout_sender_hash], params[:checkout_card_token], params[:checkout_card_name], params[:checkout_name], params[:checkout_email], params[:checkout_cpf], params[:checkout_ddd], params[:checkout_telefone], params[:checkout_card_parcelas], params[:checkout_nascimento], params[:address][:zip_code], params[:address][:street], params[:address][:street_number], params[:address][:complement], params[:address][:neighborhood], params[:address][:city], params[:address][:state])

            

            if payment.errors.any?
             
              puts payment.errors.join("\n")
              flash[:error] = "Erro No Pagamento #{payment.errors.join("\n")}"

              redirect_to :action => 'new'
            else
              puts "=> Transaction"
              puts "  code: #{payment.code}"
              puts "  reference: #{payment.reference}"

              puts "---------------PAGAMENTO---------------> #{payment}"

              @transaction.pagseguro_transaction_reference = payment.reference
              @transaction.pagseguro_transaction_code = payment.code

              unless payment.payment_link.blank?
                @transaction.pagseguro_transaction_url = payment.payment_link
              end
              # 
              @transaction.save

              redirect_to :action => 'success', reference_order: payment.reference
             
            end

          end

        end
      end
    else
      # flash[:error] = "Para poder efetuar compras é necessário estar logado."
      session[:after_redirect] = cart_path(current_cart)
      redirect_to cart_path(current_cart, login_modal: true)
    end
  end

  # def create
  #   if user_signed_in?
  #     if current_user.cpf.blank?
  #       flash[:error] = "Para poder efetuar compras é necessário que um CPF seja cadastrado."
  #       session[:after_redirect] = cart_path(current_cart)
  #       redirect_to edit_user_registration_path(current_user)
  #     elsif current_user.last_name.blank?
  #       flash[:error] = "Para poder efetuar compras é necessário que o seu nome esteja cadastrado com o sobrenome também."
  #       session[:after_redirect] = cart_path(current_cart)
  #       redirect_to edit_user_registration_path(current_user)
  #     else
  #       @cart = get_cart
  #       if @cart.shipping_hash.blank?
  #         # flash[:error] = "Antes de comprar, por favor preencha o seu CEP e clique em calcular frete."
  #         redirect_to cart_path(@cart, no_shipping: true)
  #       else
  #         @transaction = @cart.transactions.new

  #         payment = @cart.create_pagseguro(notification_transactions_url, success_transactions_url)

  #         if payment.nil?
  #           flash[:error] = "Ocorreu algum erro com os seus dados. Tente novamente."
  #           redirect_to @cart
  #         else
  #           response = payment.register

  #           if response.errors.any?
  #             flash[:error] = "Ocorreu algum erro."
  #             redirect_to @cart
  #           else
  #             @transaction.pagseguro_transaction_reference = payment.reference
  #             @transaction.pagseguro_transaction_code = response.code
  #             @transaction.pagseguro_transaction_url = response.url
  #             @transaction.save

  #             redirect_to response.url
  #           end
  #         end
  #       end
  #     end
  #   else
  #     # flash[:error] = "Para poder efetuar compras é necessário estar logado."
  #     session[:after_redirect] = cart_path(current_cart)
  #     redirect_to cart_path(current_cart, login_modal: true)
  #   end
  # end



  def success
    @success_buy = true

    if user_signed_in?
      # @buy_cart = current_user.closed_carts.order('updated_at DESC').first
      @transaction = Transaction.find_by_pagseguro_transaction_reference(params[:reference_order])



      unless @transaction.nil?

        @buy_cart = Cart.find(@transaction.cart_id)

        if @buy_cart.user_id == current_user.id

          @total_value = @buy_cart.total_price / 100.0

          @url_popup = nil

          unless @transaction.pagseguro_transaction_url.nil?
            @url_popup = @transaction.pagseguro_transaction_url
          end

        else

          flash.now[:error] = "Operação Proibida"
          redirect_to root_path

        end

      else

        flash.now[:error] = "Não existe transação com essa referência"
        redirect_to root_path

      end
    else
      flash.now[:error] = "Você precisa estar logado para acessar essa página."
      redirect_to root_path
    end
    #render 'static_pages/home'
  end

  def notification
    puts "NOTIFICATIONCODE ---->   #{params[:notificationCode]}"

    transaction = PagSeguro::Transaction.find_by_notification_code(params[:notificationCode])

    puts transaction

    @transaction = Transaction.find_by_pagseguro_transaction_reference(transaction.reference)
    @transaction.update_column(:pagseguro_transaction_hash, transaction)
    @transaction.reload

    if transaction.errors.empty?
      @transaction.status = transaction.status.id.to_i
      @transaction.save
    end

    render nothing: true, status: 200
  end


  def address_params
    params.require(:address).permit(:zip_code, :street, :street_number, :complement, :neighborhood, :city, :state).merge(owner_id: current_user.id, owner_type: "User")
  end

  

end

app/views/transactions/index.html.haml
= render 'users/account_header', selected: :transactions

- if @carts.empty?
  .container.text-center.no-transactions
    %p Você não possui nenhum pedido pago.
- else
  .container.transactions-table
    .row.title-area
      .col-xs-15
        .row
          .col-xs-15.transaction-table-title Data
          .col-xs-15.transaction-table-title Código do Pedido
      .col-xs-15
        .row
          .col-xs-15.transaction-table-title Quantidade
          .col-xs-15.transaction-table-title Status
    - @carts.each_with_index do |c, i|
      - transaction = c.transactions.last
      .transactions-accordion{ id: "transactions-accordion#{i}" }
        = link_to "#collapse#{i}", data: { toggle: 'collapse', parent: "#transactions-accordion#{i}" }, class: 'collapsed transactions-row' do
          .row.content-area
            .col-xs-15
              .row
                .col-xs-15.transaction-table-content.date-info
                  .vertical-aligned
                    %p= c.payment_date.strftime("%d/%m/%Y")
                    %p= c.payment_date.strftime("%H:%M")
                .col-xs-15.transaction-table-content.reference-info
                  .vertical-aligned= transaction.pagseguro_transaction_reference
            .col-xs-15
              .row
                .col-xs-15.transaction-table-content.items-info
                  .vertical-aligned= c.total_items
                .col-xs-15.transaction-table-content.status-info
                  .vertical-aligned= transaction.status_translation
        - if c.tracking_code.present?
          .track= link_to 'Acompanhar Pedido', "http://websro.correios.com.br/sro_bin/txect01$.QueryList?P_LINGUA=001&P_TIPO=001&P_COD_UNI=#{c.tracking_code}"
        .collapse.transaction{ id: "collapse#{i}" }
          - c.cart_items.each do |ci|
            .row.transaction-cart-item
              .col-xs-20.col-xs-offset-5
                .row
                  .col-xs-8.text-center= image_tag ci.photo, class: 'img-circle'
                  .col-xs-16.col-xs-offset-6.text-center
                    %p.name= ci.product_name
                    %p.artist= "por #{ci.artist_name}"
                    %p.values
                      %span= "em #{ci.values_names.join(' | ')} | "
                      %span= "Tamanho #{ci.size}"
                    %p.no-discount-price
                      - if ci.discount_in_cents > 0 || ci.with_discount_from_coupon?
                        %span.line-through= "de #{ci.unit_price_in_cents.to_brazilian_currency}"
                        %span= "por"
                      - else
                        %span Preço unitário:
                      %span= "#{ci.unit_price_with_coupon.to_brazilian_currency}"
                    %p.price= "Quantidade: #{ci.amount}, Total: #{ci.total_price_with_coupon.to_brazilian_currency}"
          .row.transaction-total-areas
            .col-xs-20.col-xs-offset-5.padding-50
              .row
                .col-xs-15.text-left.total-title Subtotal
                .col-xs-15.text-right.total-value= c.total_price_no_shipping_no_discount.to_brazilian_currency
              .row
                .col-xs-15.text-left.total-title Frete
                .col-xs-15.text-right.total-value= c.shipping_price_in_cents.to_brazilian_currency
              .row
                .col-xs-15.text-left.total-title Desconto
                .col-xs-15.text-right.total-value= c.discount.to_brazilian_currency
              .row.total-final
                .col-xs-15.text-left.total-title Total
                .col-xs-15.text-right.total-value= c.total_price.to_brazilian_currency

app/views/transactions/success.html.erb
<div class="pagina-obrigado">
	<div class="container">

		<div class="row">

			<h1>Obrigado por comprar na Mesclado</h1>

			<p>Você receberá um e-mail com o status da transação.</p>

			<% unless @url_popup.nil? %>
				<p>Para efetuar seu pagamento, clique no botão abaixo para visualizar o boleto!</p>
				<%= link_to 'Ver Boleto', @url_popup, target: "_blank", class: "ver_boleto" %>
			<% end %>


			<p>Verifique todos os seus pedidos em: <%= link_to 'Minha conta', transactions_index_path %></p>

			

		</div>

	</div>
</div>