config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations', omniauth_callbacks: 'users/omniauth_callbacks', passwords: 'users/passwords' }

  resources :newsletters, only: [:create]
  resources :contacts, only: [:new, :create], path: 'contato', path_names: { :new => 'novo' }

  resources :static_pages, only: [:show], path: 'institucional'
  get 'sobre', controller: 'static_pages', action: 'about', path: 'sobre', as: :about
  get 'pontos-de-venda', controller: 'static_pages', action: 'pos', path: 'pontos-de-venda', as: :pos

  resources :products, only: [:index, :show], path: 'produtos' do
    collection do
      get 'search', as: :search, path: 'busca'
      get 'page', as: :page, path: 'pagina'
    end
    resources :favorites, only: [:create]
  end

  resources :carts, only: [:show], path: 'carrinho' do
    resources :cart_items, only: [:create, :update, :destroy], path: 'itens'
    collection do
      get 'set_shipping_method', as: :set_shipping_method, path: 'frete-selecionado'
    end
  end

  resource :carts, only: [], path: '' do
    collection do
      get 'check_shipping_price', as: :check_shipping_price, path: 'calcular-frete'
    end
  end

  resource :transactions, only: [:new], path: 'transacoes' do
    collection do
      post 'notification', as: :notification, path: 'notificacao'
      post 'create', as: :create, path: 'create'
      post 'new', as: :new, path: 'new'
      get 'success', as: :success, path: 'obrigado'
    end
  end

  get 'transacoes', to: 'transactions#index', as: :transactions_index

  resources :coupons, only: [], path: 'cupons' do
    collection do
      get 'add', as: :add, path: 'adicionar'
    end
  end

  resources :favorites, only: [:index, :destroy], path: 'favoritos'

  resources :artists, only: [:index], path: 'artistas' do
    collection do
      get 'page', as: :page, path: 'pagina'
    end
  end
  resources :artists, only: [:show], path: '/'

  mount NewRelicPing::Engine => '/status'

  root to: 'static_pages#show', id: '1'

end

app/models/product.rb
class Product < ActiveRecord::Base
  include PgSearch
  multisearchable :against => [:name], if: lambda { |record| record.active }
  pg_search_scope :kinda, :against => [:name], using: { trigram: { any_word: true, treshold: 0.2 } }

  extend FriendlyId
  friendly_id :slug_candidates, use: [:slugged, :reserved, :history], sequence_separator: ''

  acts_as_paranoid

  # scope :ready, -> { joins(product_variations: :product_variation_photos).select('DISTINCT(products.id), products.artist_id, products.slug, products.deleted_at, products.name, products.active, products.price_in_cents').active }
  scope :ready, -> { joins(product_variations: :product_variation_photos).uniq.active }

  scope :active, -> { where(active: true) }
  scope :inactive, -> { where(active: false) }
  scope :deleted, -> { only_deleted }
  scope :public_ones, -> { where(public: true) }
  scope :private_ones, -> { where(public: false) }

  scope :highlight, -> { where(highlight: true) }

  attr_accessor :string_keywords

  belongs_to :artist, -> { with_deleted }

  has_many :product_variations, dependent: :destroy
  accepts_nested_attributes_for :product_variations, allow_destroy: true

  has_many :product_promotions, inverse_of: :product

  has_and_belongs_to_many :keywords
  accepts_nested_attributes_for :keywords

  has_one :meta_info, as: :owner, dependent: :destroy
  accepts_nested_attributes_for :meta_info, allow_destroy: true

  has_and_belongs_to_many :product_variation_types, join_table: 'products_product_variation_types', inverse_of: :products

  has_many :product_photos, dependent: :destroy
  accepts_nested_attributes_for :product_photos, allow_destroy: true

  validates_presence_of :name, :artist, :price_in_cents, :product_photos, :product_code

  before_validation :set_variation_types
  # after_initialize :set_string_keywords

  after_save :create_keywords, :change_children_active_state
  after_commit :create_product_variations, on: :create
  after_commit :update_children_values_if_needed, on: :update

  before_restore :restore_children

  def ready?
    self.product_variations.ready.any?
  end

  def total_value
    self.price_in_cents - self.discount
  end

  def discount
    if possible_promotions.present?
      best_promotion.advantage_profile.discount(self.price_in_cents)
    else
      0
    end
  end

  def best_promotion
    self.possible_promotions.sort_by { |x| x.advantage.advantage_profile.discount(self.price_in_cents) }.last
  end

  def possible_promotions
    product_ids = product_promotions.pluck(:id)
    artist_ids = artist_promotions.pluck(:id)

    Promotion.where(id: (product_ids + artist_ids)).uniq
  end

  def product_promotions
    Promotion.valid.joins(:product_promotion).where('product_promotions.product_id = ? OR product_promotions.all_products = ?', self.id, true).includes(:coupon).where(coupons: { promotion_id: nil })
  end

  def artist_promotions
    Promotion.joins(:artist_promotion).where(artist_promotions: { artist_id: self.artist_id }).includes(:coupon).where(coupons: { promotion_id: nil })
  end

  def coupon_promotions

  end

  def price_in_cents=(value)
    if value.class.to_s.downcase == 'string'
      value = value.gsub(/\D/, '').to_i
    end
    super
  end

  def photo
    first = self.product_photos.limit(1).first

    if first.nil?
      nil
    else
      first.photo
    end
  end

  def product_variations
    self.destroyed? ? super.with_deleted : super
  end

  def product_variation
    vars = self.product_variations.ready.limit(1)

    vars.where(default: true).first || vars.first
  end

  def product_photos
    self.destroyed? ? super.with_deleted : super
  end

  def meta_info
    self.destroyed? ? MetaInfo.with_deleted.where(owner_id: self.id, owner_type: self.class).first : super
  end

  def keywords_to_s
    self.keywords.map { |x| "#{x.name}" }.join(' ')
  end

  def name
    "#{super}#{self.active ? '' : ' (Desativado)'}"
  end

  def active=(value)
    value = active_logic(value)
    super
  end

  def active_logic value = nil
    if value == "0"
      value = false
    elsif value == "1"
      value = true
    end
    value = self.active if value.nil?
    if self.artist.present?
      value and self.artist.active
    else
      value
    end
  end

  def update_children_values_if_needed
    children_values = self.product_variations.map { |x| x.product_variation_type_values }.flatten.uniq
    values = self.product_variation_types.map { |x| x.product_variation_type_values }.flatten.uniq

    values_to_remove = children_values - values
    values_to_add = values - children_values

    unless values_to_remove.empty? and values_to_add.empty?
      self.product_variations.each do |pv|
        pv.really_destroy!
      end
      ProductVariation.create_all_variations_from_product(self.id)
    end
  end

  def possible_values
    grouped_values = ProductVariationTypeValue.joins(:product_variations).where(product_variations: { id: self.product_variations.ready.map { |x| x.id } }).uniq.includes(:product_variation_type).includes(:product_variation_sizes).uniq.sort_by { |x| x.product_variation_type.position }.group_by { |x| x.product_variation_type }

    grouped_values.each do |k, v|
      grouped_values[k].sort_by! { |x| x.position }
    end

    sizes = grouped_values.map { |k, v| v.map { |x| x.product_variation_sizes } }.flatten.uniq.sort_by! { |x| x.position }
    grouped_values['sizes'] = sizes

    grouped_values
  end

  private

    def set_string_keywords
      self.string_keywords || self.keywords_to_s
    end

    def change_children_active_state
      if self.active_changed?
        self.product_variations.each do |p|
          p.update_column(:active, p.active_logic)
        end
      end
    end

    def restore_children
      ProductPhoto.restore self.product_photos.only_deleted.map { |x| x.id }
      ProductVariation.restore self.product_variations.only_deleted.map { |x| x.id }
      MetaInfo.restore self.meta_info.id
    end

    def create_keywords
      self.string_keywords = self.string_keywords || self.keywords_to_s
      self.string_keywords.downcase!

      if self.string_keywords != self.keywords_to_s
        words = self.string_keywords.split(' ')
        key_names = self.keywords.map { |x| x.name }
        key_names.each_with_index do |kn|
          unless words.include? kn
            self.keywords.delete Keyword.unscoped.find_by_name(kn)
          else
            words.delete(kn)
          end
        end
        words.each do |w|
          kw = Keyword.unscoped.find_by_name(w)
          if kw.present?
            if kw.destroyed?
              self.keywords.push Keyword.restore(kw.id)
            else
              self.keywords.push kw
            end
          else
            self.keywords.create(name: w)
          end
        end
      end
    end

    def should_generate_new_friendly_id?
      new_record? || slug.blank?
    end

    def set_variation_types
      if self.product_variation_types.empty?
        self.product_variation_types = ProductVariationType.all
      end
    end

    def create_product_variations
      ProductVariation.create_all_variations_from_product(self.id)
    end

    def slug_candidates
      [
        :name_no_spaces,
        [:name_no_spaces, :sub_title],
        [:name_no_spaces, :sub_title, :product_code]
      ]
    end

    def name_no_spaces
      self.name.gsub(' ', '')
    end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    if params[:tag].present?
      @products = Product.where(id: Keyword.includes(:products).where(name: params[:tag]).map { |x| x.products.ready.public_ones.includes(:artist) }.flatten.map { |x| x.id }).order('highlight DESC, RANDOM()').includes(:artist)
    else
      @products = Product.where(id: Product.ready.public_ones.pluck(:id)).order('highlight DESC, RANDOM()').includes(:artist)
    end

    if params[:price].present?
      @products = @products.order("price_in_cents #{params[:price]}")
    end

    @keywords = Keyword.includes(:products).all.reject { |x| x.products.ready.public_ones.empty? }
  end

  def page
    if request.xhr?
      products = Product.find params[:items]
      render partial: 'products/page', locals: { list: products }
    end
  end

  def show
    @product = Product.find(params[:id])
    @product_variation = @product.product_variation

    @other_products = Product.where(id: Product.ready.public_ones.where.not(id: @product.id).pluck(:id)).limit(4).order('RANDOM()')
  end

  def search
    @artists = Artist.active.public_ones.kinda(params[:search])
    @products = Product.ready.public_ones.kinda(params[:search])

    @results = PgSearch.multisearch(params[:search]).group_by { |x| x.searchable_type }

    # binding.pry

    if @results['Artist'].present?
      @artists += @results['Artist'].map { |x| x.searchable }.select { |x| x.public? }
    end

    if @results['Product'].present?
      @products += @results['Product'].map { |x| x.searchable }.reject { |x| x.product_variation.nil? or !(x.public?) }
    end

    @artists = Artist.where(id: @artists.map { |x| x.id }).uniq
    @products = Product.where(id: @products.map { |x| x.id }).uniq

    render partial: 'products/search'
  end
end

app/views/products/_page.html.haml
- with_ga ||= false

.page-container.active{ style: ('position: relative;' if params[:page] == 0 and list.length < 9), data: { page: params[:page] } }
  - list.each_slice(3) do |slice|
    .row.products-row
      = render partial: 'products/thumb', collection: slice, as: :product, locals: { div_style: 'display: inline-block', with_ga: with_ga }
      -# - slice.each do |p|
      -#   = render 'products/thumb', product: p

app/views/products/_search.html.haml
.search-content
  .close-search= fa_icon 'times 4x'
  - unless @products.empty? and @artists.empty?
    %ul.nav.nav-tabs{ role: 'tablist' }
      - if @products.present?
        %li.active= link_to 'Artes', '#products', role: 'tab', :'data-toggle' => 'tab'
      - if @artists.present?
        %li{ class: ('active' if @products.empty?) }= link_to 'Artistas', '#artists', role: 'tab', :'data-toggle' => 'tab'

    .tab-content
      - if @products.present?
        .tab-pane.fade.active.in#products= render 'shared/list', list: @products, n: 9, page: 'products/page', ajax_url: '/produtos/pagina'
      - if @artists.present?
        .tab-pane.fade#artists{ class: ('active in' if @products.empty?) }= render 'shared/list', list: @artists, n: 12, page: 'artists/page', ajax_url: '/artistas/pagina'
  - else
    %p.no-results.text-center Nenhum resultado foi encontrado.

app/views/products/_thumb.html.haml
- div_class ||= ''
- div_style ||= ''
- with_ga ||= false

%div{ class: div_class, style: div_style }
  = link_to product, class: 'product-thumb', onclick: "ga('send', 'event', 'Home', 'Galeria', 'Comprar');" do
    = image_tag product.photo.url(:standard)
    .overlay-area
      - pv = product.product_variation
      - if pv.present? and pv.photo.present?
        = image_tag pv.photo.url(:thumb), class: 'product-thumb-image'
      / .thumb-details.details-top.text-center
      /   %p.product-name= product.name
      /   %p.artist-name
      /     %span por
      /     = link_to product.artist.name, product.artist
      / = link_to 'Comprar', product, class: 'black-button'
      .thumb-details.text-center
        .row
          .col-xs-18
            %p.product-name= product.name
            / %p.artist-name
            /   %span por
            /   = link_to product.artist.name, product.artist
          .col-xs-11.col-xs-offset-1
            - if product.possible_promotions.present?
              %p.price-no-discount= "de #{product.price_in_cents.to_brazilian_currency}"
              %p.price= "por #{product.total_value.to_brazilian_currency}"
            - else
              %p.price= product.total_value.to_brazilian_currency

app/views/products/_variation_options.html.haml
.variation-options{ data: { product: product.id } }
  - product.possible_values.each do |k, v|
    .variation-line
      .variation-title= k == 'sizes' ? 'Tamanhos' : k.name
      - type_value = k == 'sizes' ? 0 : k.id
      .variation-values{ data: { type: type_value } }
        - some_selected = false
        - v.each_with_index do |value, i|
          - unless product_variation.can_have_value?(type_value, value.id) and type_value == 0 and some_selected == false
            - selected = product_variation.selected_value?(type_value, value.id)
            / - some_selected = true
            / - selected = true
          / - else
          .value-icon{ class: "#{'selected' if selected}#{'inactive' unless product_variation.can_have_value?(type_value, value.id)}", data: { value: value.id, related: value.related_values_for(product).to_a } }
            - if value.photo.present?
              = image_tag value.photo.url(:icon), class: 'not-selected-photo'
              = image_tag value.selected_photo.url(:icon), class: 'selected-photo'
            - else
              .color-image{ style: "background-color: #{value.value}" }

= link_to 'Tabela de Medidas', 'javaScript:void(0);', onClick: "$('#product-metrics').fadeIn('fast');", class: 'metrics-link'

app/views/products/index.html.haml
- meta title: 'Artes', description: 'Mais de 600 estampas com estilos variados'

.products-organizer.text-center
  = render 'outsiders/facebook_pixel_categories'
  - if @keywords.present?
    .organize-products.keywords
      .organizer-bt
        Tags
        = fa_icon 'angle-down 2x'
      .organizer-popup
        .search-keywords
          %input{ type: 'text' }
          = fa_icon 'search'
        .possible-keywords
          - @keywords.each do |k|
            = link_to k.name.capitalize, products_path(tag: k.name), data: { key: k.name }
  .divider
  / .organize-products.price
  /   .organizer-bt
  /     Preço
  /     = fa_icon 'angle-down 2x'
  /   .organizer-popup
  /     = link_to 'Crescente', products_path(price: 'ASC')
  /     = link_to 'Decrescente', products_path(price: 'DESC')
  = link_to products_path, class: 'random-products-link' do
    Random
    = fa_icon 'random'

= render 'shared/list', list: @products, n: 9, page: 'products/page', ajax_url: '/produtos/pagina'

app/views/products/show.html.haml
- meta og: { title: @product.name, type: 'website', url: request.url, image: @product.photo.url(:standard), description: ActionController::Base.helpers.strip_tags(@product.technical_details.html_safe) }, title: @product.name

.container.product-show
  = render 'outsiders/facebook_pixel_product'
  .row
    .col-xs-15
      = image_tag @product_variation.photo.url(:original), class: 'product-variation-photo in'
      = image_tag '', class: 'product-variation-photo absolute out'
      = image_tag @product.photo.url(:standard), class: 'product-photo'
    .col-xs-14.product-show-info
      %h1= @product.name
      %h3
        por
        = link_to @product.artist.name.upcase, @product.artist
      .price
        - if @product_variation.product.discount > 0
          %p.discount-from= "De #{@product_variation.price_in_cents_no_discount.to_brazilian_currency} por"
        %span.white R$
        %span.black= @product_variation.price_in_cents.to_brazilian_currency.gsub('R$ ', '')
      .bottom-area
        = render partial: 'variation_options', locals: { product: @product, product_variation: @product_variation }
        .buy-button-row
          = link_to cart_cart_items_path(current_cart, redirect_to_cart: true), method: :post, class: 'buy-button', remote: true, onclick: "window.start_loading();" do
            = fa_icon 'shopping-cart'
            Comprar
          - if user_signed_in?
            - favorite = current_user.has_favorite?(@product)
            - path = favorite.present? ? favorite_path(favorite) : product_favorites_path(@product)
            - method = favorite.present? ? :delete : :post
            = link_to path, class: "favorite-button #{'yellow' if favorite.present?}", method: method, remote: true, onclick: 'window.start_loading();' do
              = fa_icon 'star'


.ajax-photos
  - @product.product_variations.ready.each do |pv|
    .product-variation{ data: { :'product-variation-id' => pv.id, url: pv.photo.url(:standard), values: pv.product_variation_type_values.pluck(:id) } }


- if !@product.technical_details.blank? or !@product.inspiration.blank?
  .container.product-details
    %ul.nav.nav-tabs{ role: 'tablist' }
      - if !@product.technical_details.blank?
        %li.active= link_to 'Descrição', '#technical_details', role: 'tab', :'data-toggle' => 'tab'
      - if !@product.inspiration.blank?
        %li{ class: ('active' if @product.technical_details.blank?) }= link_to 'Inspiração', '#inspiration', role: 'tab', :'data-toggle' => 'tab'

    .tab-content
      - if !@product.technical_details.blank?
        .tab-pane.fade.active.in#technical_details= @product.technical_details.html_safe
      - if !@product.inspiration.blank?
        .tab-pane.fade#inspiration{ class: ('active in' if @product.technical_details.blank?) }=  @product.inspiration.html_safe

.container.other-products
  .row.other-products-line
    .col-xs-30
      .other-products-title Outras Artes
      %hr
  .row.text-center
    = render partial: 'products/thumb', collection: @other_products, as: :product, locals: { div_style: 'display: inline-block;' }
    -# - @other_products.each do |product|
    -#   = render 'products/thumb', product: product


#product-metrics{ onClick: "$(this).fadeOut('fast');" }
  = image_tag 'tabela-de-tamanhos.jpg'


#variations-modal.modal.fade{ tabindex: '-1', role: 'dialog', :'aria-labelledby' => 'modal', :'aria-hidden' => 'true' }
  .modal-dialog.modal-md
    .close{ type: 'button', data: { dismiss: 'modal' } }
      %span{ :'aria-hidden' => 'true' } &times;
      %span.sr-only Close
    .modal-content.product-show
      %h2 Escolha os detalhes do produto para poder adiciona-lo ao carrinho.
      = render partial: 'variation_options', locals: { product: @product, product_variation: @product_variation }
      .buy-button-row
        = link_to cart_cart_items_path(current_cart), method: :post, class: 'buy-button', remote: true, onclick: "window.start_loading(); ga('send', 'event', 'Produto', '#{@product.name}', 'To Carrinho');" do
          = fa_icon 'shopping-cart'
          Comprar